class RscActivePictureKeepAspect;
class RscMainMenuSpotlight;
class RscStandardDisplay;
class RscText;

class RscDisplayMain : RscStandardDisplay {
    class controls {
        class Spotlight1 { // : RscMainMenuSpotlight {
            idc = 1021;
            x = "0.5 - (1.5 *   10) *   (pixelW * pixelGridNoUIScale * 2) -     (2 * pixelW)";
            class Controls {
                class GroupPicture {
                    class Controls {
                        class Picture {
                            text = "\a3\Ui_f\data\GUI\Rsc\RscDisplayMain\spotlight_2_ca.paa";
                            idc = 1023;
                            x = 0;
                            y = 0;
                            w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                            h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                            style = "0x30 + 0x800";
                            deletable = 0;
                            fade = 0;
                            access = 0;
                            type = 0;
                            colorBackground[] = {0, 0, 0, 0};
                            colorText[] = {1, 1, 1, 1};
                            font = "TahomaB";
                            sizeEx = 0;
                            lineSpacing = 0;
                            fixedWidth = 0;
                            shadow = 0;
                            tooltipColorText[] = {1, 1, 1, 1};
                            tooltipColorBox[] = {1, 1, 1, 1};
                            tooltipColorShade[] = {0, 0, 0, 0.65};
                        };
                        class Video {
                            text = "\a3\Ui_f\Video\spotlight_2.ogv";
                            idc = 1024;
                            show = 0;
                            x = 0;
                            y = 0;
                            w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                            h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                            autoplay = 1;
                            loops = 1;
                            deletable = 0;
                            fade = 0;
                            access = 0;
                            type = 0;
                            style = 48;
                            colorBackground[] = {0, 0, 0, 0};
                            colorText[] = {1, 1, 1, 1};
                            font = "TahomaB";
                            sizeEx = 0;
                            lineSpacing = 0;
                            fixedWidth = 0;
                            shadow = 0;
                            tooltipColorText[] = {1, 1, 1, 1};
                            tooltipColorBox[] = {1, 1, 1, 1};
                            tooltipColorShade[] = {0, 0, 0, 0.65};
                        };
                    };
                    x = 0;
                    y = 0;
                    w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                    h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                    class VScrollbar {
                        width = 0;
                        color[] = {1, 1, 1, 1};
                        autoScrollEnabled = 1;
                        colorActive[] = {1, 1, 1, 1};
                        colorDisabled[] = {1, 1, 1, 0.3};
                        thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
                        arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
                        arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
                        border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
                        shadow = 0;
                        scrollSpeed = 0.06;
                        height = 0;
                        autoScrollSpeed = -1;
                        autoScrollDelay = 5;
                        autoScrollRewind = 0;
                    };
                    class HScrollbar {
                        height = 0;
                        color[] = {1, 1, 1, 1};
                        colorActive[] = {1, 1, 1, 1};
                        colorDisabled[] = {1, 1, 1, 0.3};
                        thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
                        arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
                        arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
                        border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
                        shadow = 0;
                        scrollSpeed = 0.06;
                        width = 0;
                        autoScrollEnabled = 0;
                        autoScrollSpeed = -1;
                        autoScrollDelay = 5;
                        autoScrollRewind = 0;
                    };
                    deletable = 0;
                    fade = 0;
                    type = 15;
                    idc = -1;
                    shadow = 0;
                    style = 16;
                };
                class GroupHover {
                    class Controls {
                        class Overlay {
                            text = "\a3\Ui_f\data\GUI\Rsc\RscDisplayMain\hover_ca.paa";
                            colorText[] = {0, 0, 0, 0.5};
                            x = 0;
                            y = 0;
                            w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                            h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                            deletable = 0;
                            fade = 0;
                            access = 0;
                            type = 0;
                            idc = -1;
                            style = 48;
                            colorBackground[] = {0, 0, 0, 0};
                            font = "TahomaB";
                            sizeEx = 0;
                            lineSpacing = 0;
                            fixedWidth = 0;
                            shadow = 0;
                            tooltipColorText[] = {1, 1, 1, 1};
                            tooltipColorBox[] = {1, 1, 1, 1};
                            tooltipColorShade[] = {0, 0, 0, 0.65};
                        };
                        class LineLeft {
                            colorBackground[] = {1, 1, 1, 1};
                            x = 0;
                            y = 0;
                            w = "pixelW";
                            h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                            deletable = 0;
                            fade = 0;
                            access = 0;
                            type = 0;
                            idc = -1;
                            colorText[] = {1, 1, 1, 1};
                            text = "";
                            fixedWidth = 0;
                            style = 0;
                            shadow = 1;
                            colorShadow[] = {0, 0, 0, 0.5};
                            font = "RobotoCondensed";
                            SizeEx = "(         (           (           ((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
                            linespacing = 1;
                            tooltipColorText[] = {1, 1, 1, 1};
                            tooltipColorBox[] = {1, 1, 1, 1};
                            tooltipColorShade[] = {0, 0, 0, 0.65};
                        };
                        class LineRight {
                            x = "10 *   (pixelW * pixelGridNoUIScale * 2) - pixelW";
                            colorBackground[] = {1, 1, 1, 1};
                            y = 0;
                            w = "pixelW";
                            h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                            deletable = 0;
                            fade = 0;
                            access = 0;
                            type = 0;
                            idc = -1;
                            colorText[] = {1, 1, 1, 1};
                            text = "";
                            fixedWidth = 0;
                            style = 0;
                            shadow = 1;
                            colorShadow[] = {0, 0, 0, 0.5};
                            font = "RobotoCondensed";
                            SizeEx = "(         (           (           ((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
                            linespacing = 1;
                            tooltipColorText[] = {1, 1, 1, 1};
                            tooltipColorBox[] = {1, 1, 1, 1};
                            tooltipColorShade[] = {0, 0, 0, 0.65};
                        };
                        class LineTop {
                            text = "Open";
                            idc = 1027;
                            x = 0;
                            y = 0;
                            w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                            h = "(pixelH * pixelGrid * 2)";
                            colorText[] = {0, 0, 0, 1};
                            shadow = 0;
                            style = 0;
                            sizeEx = "(pixelH * pixelGrid * 2)";
                            font = "PuristaLight";
                            onLoad = "(_this select 0) ctrlsettext toupper ctrltext (_this select 0);";
                            colorBackground[] = {1, 1, 1, 1};
                            deletable = 0;
                            fade = 0;
                            access = 0;
                            type = 0;
                            fixedWidth = 0;
                            colorShadow[] = {0, 0, 0, 0.5};
                            linespacing = 1;
                            tooltipColorText[] = {1, 1, 1, 1};
                            tooltipColorBox[] = {1, 1, 1, 1};
                            tooltipColorShade[] = {0, 0, 0, 0.65};
                        };
                        class LineBottom {
                            y = "10 *   (pixelH * pixelGridNoUIScale * 2) - pixelH";
                            h = "pixelH";
                            idc = 1027;
                            x = 0;
                            w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                            colorText[] = {0, 0, 0, 1};
                            shadow = 0;
                            style = 0;
                            sizeEx = "(pixelH * pixelGrid * 2)";
                            font = "PuristaLight";
                            onLoad = "(_this select 0) ctrlsettext toupper ctrltext (_this select 0);";
                            colorBackground[] = {1, 1, 1, 1};
                            deletable = 0;
                            fade = 0;
                            access = 0;
                            type = 0;
                            text = "";
                            fixedWidth = 0;
                            colorShadow[] = {0, 0, 0, 0.5};
                            linespacing = 1;
                            tooltipColorText[] = {1, 1, 1, 1};
                            tooltipColorBox[] = {1, 1, 1, 1};
                            tooltipColorShade[] = {0, 0, 0, 0.65};
                        };
                    };
                    idc = 1025;
                    fade = 1;
                    x = 0;
                    y = 0;
                    w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                    h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                    class VScrollbar {
                        width = 0;
                        color[] = {1, 1, 1, 1};
                        autoScrollEnabled = 1;
                        colorActive[] = {1, 1, 1, 1};
                        colorDisabled[] = {1, 1, 1, 0.3};
                        thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
                        arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
                        arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
                        border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
                        shadow = 0;
                        scrollSpeed = 0.06;
                        height = 0;
                        autoScrollSpeed = -1;
                        autoScrollDelay = 5;
                        autoScrollRewind = 0;
                    };
                    class HScrollbar {
                        height = 0;
                        color[] = {1, 1, 1, 1};
                        colorActive[] = {1, 1, 1, 1};
                        colorDisabled[] = {1, 1, 1, 0.3};
                        thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
                        arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
                        arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
                        border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
                        shadow = 0;
                        scrollSpeed = 0.06;
                        width = 0;
                        autoScrollEnabled = 0;
                        autoScrollSpeed = -1;
                        autoScrollDelay = 5;
                        autoScrollRewind = 0;
                    };
                    deletable = 0;
                    type = 15;
                    shadow = 0;
                    style = 16;
                };
                class TextBackground {
                    idc = 1029;
                    text = "\a3\Ui_f\data\GUI\Rsc\RscDisplayMain\spotlight_backgroundText_ca.paa";
                    colorText[] = {0, 0, 0, 0.5};
                    x = 0;
                    y = 0;
                    w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                    h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                    deletable = 0;
                    fade = 0;
                    access = 0;
                    type = 0;
                    style = 48;
                    colorBackground[] = {0, 0, 0, 0};
                    font = "TahomaB";
                    sizeEx = 0;
                    lineSpacing = 0;
                    fixedWidth = 0;
                    shadow = 0;
                    tooltipColorText[] = {1, 1, 1, 1};
                    tooltipColorBox[] = {1, 1, 1, 1};
                    tooltipColorShade[] = {0, 0, 0, 0.65};
                };
                class Text {
                    text = "Quick Play";
                    idc = 1028;
                    size = "1.00 *  (pixelH * pixelGridNoUIScale * 2)";
                    shadow = 2;
                    x = 0;
                    y = 0;
                    w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                    h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                    class Attributes {
                        align = "center";
                        color = "#ffffff";
                        font = "PuristaBold";
                    };
                    deletable = 0;
                    fade = 0;
                    access = 0;
                    type = 13;
                    style = 0;
                    colorText[] = {1, 1, 1, 1};
                };
                class Button {
                    idc = 1026;
                    colorBackground[] = {0, 0, 0, 0};
                    colorBackgroundActive[] = {0, 0, 0, 0};
                    colorBackgroundDisabled[] = {0, 0, 0, 0};
                    colorFocused[] = {0, 0, 0, 0};
                    colorDisabled[] = {0, 0, 0, 0};
                    x = 0;
                    y = 0;
                    w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                    h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                    deletable = 0;
                    fade = 0;
                    access = 0;
                    type = 1;
                    text = "";
                    colorText[] = {1, 1, 1, 1};
                    colorShadow[] = {0, 0, 0, 0};
                    colorBorder[] = {0, 0, 0, 1};
                    soundEnter[] = {"\A3\ui_f\data\sound\RscButton\soundEnter", 0.09, 1};
                    soundPush[] = {"\A3\ui_f\data\sound\RscButton\soundPush", 0.09, 1};
                    soundClick[] = {"\A3\ui_f\data\sound\RscButton\soundClick", 0.09, 1};
                    soundEscape[] = {"\A3\ui_f\data\sound\RscButton\soundEscape", 0.09, 1};
                    style = 2;
                    shadow = 2;
                    font = "RobotoCondensed";
                    sizeEx = "(         (           (           ((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
                    url = "";
                    offsetX = 0;
                    offsetY = 0;
                    offsetPressedX = 0;
                    offsetPressedY = 0;
                    borderSize = 0;
                };
            };
            fade = 1;
            y = "0.5 - (    10 / 2) *   (pixelH * pixelGridNoUIScale * 2)";
            w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
            h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
            class VScrollbar {
                width = 0;
                color[] = {1, 1, 1, 1};
                autoScrollEnabled = 1;
                colorActive[] = {1, 1, 1, 1};
                colorDisabled[] = {1, 1, 1, 0.3};
                thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
                arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
                arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
                border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
                shadow = 0;
                scrollSpeed = 0.06;
                height = 0;
                autoScrollSpeed = -1;
                autoScrollDelay = 5;
                autoScrollRewind = 0;
            };
            class HScrollbar {
                height = 0;
                color[] = {1, 1, 1, 1};
                colorActive[] = {1, 1, 1, 1};
                colorDisabled[] = {1, 1, 1, 0.3};
                thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
                arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
                arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
                border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
                shadow = 0;
                scrollSpeed = 0.06;
                width = 0;
                autoScrollEnabled = 0;
                autoScrollSpeed = -1;
                autoScrollDelay = 5;
                autoScrollRewind = 0;
            };
            deletable = 0;
            type = 15;
            shadow = 0;
            style = 16;
        };
        class Spotlight2 { // : RscText {
            idc = 1020;
            x = "0.5 - (0.5 *   10) *   (pixelW * pixelGridNoUIScale * 2)";
            y = "0.5 - (    10 / 2) *   (pixelH * pixelGridNoUIScale * 2)";
            w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
            h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
            show = 0;
            deletable = 0;
            fade = 0;
            access = 0;
            type = 0;
            colorBackground[] = {0, 0, 0, 0};
            colorText[] = {1, 1, 1, 1};
            text = "";
            fixedWidth = 0;
            style = 0;
            shadow = 1;
            colorShadow[] = {0, 0, 0, 0.5};
            font = "RobotoCondensed";
            SizeEx = "(         (           (           ((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
            linespacing = 1;
            tooltipColorText[] = {1, 1, 1, 1};
            tooltipColorBox[] = {1, 1, 1, 1};
            tooltipColorShade[] = {0, 0, 0, 0.65};
        };
        class Spotlight3 { // : RscMainMenuSpotlight {
            idc = 1022;
            x = "0.5 + (0.5 *   10) *   (pixelW * pixelGridNoUIScale * 2) +     (2 * pixelW)";
            class Controls {
                class GroupPicture {
                    class Controls {
                        class Picture {
                            text = "\a3\Ui_f\data\GUI\Rsc\RscDisplayMain\spotlight_3_ca.paa";
                            idc = 1023;
                            x = 0;
                            y = 0;
                            w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                            h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                            style = "0x30 + 0x800";
                            deletable = 0;
                            fade = 0;
                            access = 0;
                            type = 0;
                            colorBackground[] = {0, 0, 0, 0};
                            colorText[] = {1, 1, 1, 1};
                            font = "TahomaB";
                            sizeEx = 0;
                            lineSpacing = 0;
                            fixedWidth = 0;
                            shadow = 0;
                            tooltipColorText[] = {1, 1, 1, 1};
                            tooltipColorBox[] = {1, 1, 1, 1};
                            tooltipColorShade[] = {0, 0, 0, 0.65};
                        };
                        class Video {
                            text = "\a3\Ui_f\Video\spotlight3.ogv";
                            idc = 1024;
                            show = 0;
                            x = 0;
                            y = 0;
                            w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                            h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                            autoplay = 1;
                            loops = 1;
                            deletable = 0;
                            fade = 0;
                            access = 0;
                            type = 0;
                            style = 48;
                            colorBackground[] = {0, 0, 0, 0};
                            colorText[] = {1, 1, 1, 1};
                            font = "TahomaB";
                            sizeEx = 0;
                            lineSpacing = 0;
                            fixedWidth = 0;
                            shadow = 0;
                            tooltipColorText[] = {1, 1, 1, 1};
                            tooltipColorBox[] = {1, 1, 1, 1};
                            tooltipColorShade[] = {0, 0, 0, 0.65};
                        };
                    };
                    x = 0;
                    y = 0;
                    w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                    h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                    class VScrollbar {
                        width = 0;
                        color[] = {1, 1, 1, 1};
                        autoScrollEnabled = 1;
                        colorActive[] = {1, 1, 1, 1};
                        colorDisabled[] = {1, 1, 1, 0.3};
                        thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
                        arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
                        arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
                        border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
                        shadow = 0;
                        scrollSpeed = 0.06;
                        height = 0;
                        autoScrollSpeed = -1;
                        autoScrollDelay = 5;
                        autoScrollRewind = 0;
                    };
                    class HScrollbar {
                        height = 0;
                        color[] = {1, 1, 1, 1};
                        colorActive[] = {1, 1, 1, 1};
                        colorDisabled[] = {1, 1, 1, 0.3};
                        thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
                        arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
                        arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
                        border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
                        shadow = 0;
                        scrollSpeed = 0.06;
                        width = 0;
                        autoScrollEnabled = 0;
                        autoScrollSpeed = -1;
                        autoScrollDelay = 5;
                        autoScrollRewind = 0;
                    };
                    deletable = 0;
                    fade = 0;
                    type = 15;
                    idc = -1;
                    shadow = 0;
                    style = 16;
                };
                class GroupHover {
                    class Controls {
                        class Overlay {
                            text = "\a3\Ui_f\data\GUI\Rsc\RscDisplayMain\hover_ca.paa";
                            colorText[] = {0, 0, 0, 0.5};
                            x = 0;
                            y = 0;
                            w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                            h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                            deletable = 0;
                            fade = 0;
                            access = 0;
                            type = 0;
                            idc = -1;
                            style = 48;
                            colorBackground[] = {0, 0, 0, 0};
                            font = "TahomaB";
                            sizeEx = 0;
                            lineSpacing = 0;
                            fixedWidth = 0;
                            shadow = 0;
                            tooltipColorText[] = {1, 1, 1, 1};
                            tooltipColorBox[] = {1, 1, 1, 1};
                            tooltipColorShade[] = {0, 0, 0, 0.65};
                        };
                        class LineLeft {
                            colorBackground[] = {1, 1, 1, 1};
                            x = 0;
                            y = 0;
                            w = "pixelW";
                            h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                            deletable = 0;
                            fade = 0;
                            access = 0;
                            type = 0;
                            idc = -1;
                            colorText[] = {1, 1, 1, 1};
                            text = "";
                            fixedWidth = 0;
                            style = 0;
                            shadow = 1;
                            colorShadow[] = {0, 0, 0, 0.5};
                            font = "RobotoCondensed";
                            SizeEx = "(         (           (           ((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
                            linespacing = 1;
                            tooltipColorText[] = {1, 1, 1, 1};
                            tooltipColorBox[] = {1, 1, 1, 1};
                            tooltipColorShade[] = {0, 0, 0, 0.65};
                        };
                        class LineRight {
                            x = "10 *   (pixelW * pixelGridNoUIScale * 2) - pixelW";
                            colorBackground[] = {1, 1, 1, 1};
                            y = 0;
                            w = "pixelW";
                            h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                            deletable = 0;
                            fade = 0;
                            access = 0;
                            type = 0;
                            idc = -1;
                            colorText[] = {1, 1, 1, 1};
                            text = "";
                            fixedWidth = 0;
                            style = 0;
                            shadow = 1;
                            colorShadow[] = {0, 0, 0, 0.5};
                            font = "RobotoCondensed";
                            SizeEx = "(         (           (           ((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
                            linespacing = 1;
                            tooltipColorText[] = {1, 1, 1, 1};
                            tooltipColorBox[] = {1, 1, 1, 1};
                            tooltipColorShade[] = {0, 0, 0, 0.65};
                        };
                        class LineTop {
                            text = "Create";
                            idc = 1027;
                            x = 0;
                            y = 0;
                            w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                            h = "(pixelH * pixelGrid * 2)";
                            colorText[] = {0, 0, 0, 1};
                            shadow = 0;
                            style = 0;
                            sizeEx = "(pixelH * pixelGrid * 2)";
                            font = "PuristaLight";
                            onLoad = "(_this select 0) ctrlsettext toupper ctrltext (_this select 0);";
                            colorBackground[] = {1, 1, 1, 1};
                            deletable = 0;
                            fade = 0;
                            access = 0;
                            type = 0;
                            fixedWidth = 0;
                            colorShadow[] = {0, 0, 0, 0.5};
                            linespacing = 1;
                            tooltipColorText[] = {1, 1, 1, 1};
                            tooltipColorBox[] = {1, 1, 1, 1};
                            tooltipColorShade[] = {0, 0, 0, 0.65};
                        };
                        class LineBottom {
                            y = "10 *   (pixelH * pixelGridNoUIScale * 2) - pixelH";
                            h = "pixelH";
                            idc = 1027;
                            x = 0;
                            w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                            colorText[] = {0, 0, 0, 1};
                            shadow = 0;
                            style = 0;
                            sizeEx = "(pixelH * pixelGrid * 2)";
                            font = "PuristaLight";
                            onLoad = "(_this select 0) ctrlsettext toupper ctrltext (_this select 0);";
                            colorBackground[] = {1, 1, 1, 1};
                            deletable = 0;
                            fade = 0;
                            access = 0;
                            type = 0;
                            text = "";
                            fixedWidth = 0;
                            colorShadow[] = {0, 0, 0, 0.5};
                            linespacing = 1;
                            tooltipColorText[] = {1, 1, 1, 1};
                            tooltipColorBox[] = {1, 1, 1, 1};
                            tooltipColorShade[] = {0, 0, 0, 0.65};
                        };
                    };
                    idc = 1025;
                    fade = 1;
                    x = 0;
                    y = 0;
                    w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                    h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                    class VScrollbar {
                        width = 0;
                        color[] = {1, 1, 1, 1};
                        autoScrollEnabled = 1;
                        colorActive[] = {1, 1, 1, 1};
                        colorDisabled[] = {1, 1, 1, 0.3};
                        thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
                        arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
                        arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
                        border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
                        shadow = 0;
                        scrollSpeed = 0.06;
                        height = 0;
                        autoScrollSpeed = -1;
                        autoScrollDelay = 5;
                        autoScrollRewind = 0;
                    };
                    class HScrollbar {
                        height = 0;
                        color[] = {1, 1, 1, 1};
                        colorActive[] = {1, 1, 1, 1};
                        colorDisabled[] = {1, 1, 1, 0.3};
                        thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
                        arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
                        arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
                        border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
                        shadow = 0;
                        scrollSpeed = 0.06;
                        width = 0;
                        autoScrollEnabled = 0;
                        autoScrollSpeed = -1;
                        autoScrollDelay = 5;
                        autoScrollRewind = 0;
                    };
                    deletable = 0;
                    type = 15;
                    shadow = 0;
                    style = 16;
                };
                class TextBackground {
                    idc = 1029;
                    text = "\a3\Ui_f\data\GUI\Rsc\RscDisplayMain\spotlight_backgroundText_ca.paa";
                    colorText[] = {0, 0, 0, 0.5};
                    x = 0;
                    y = 0;
                    w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                    h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                    deletable = 0;
                    fade = 0;
                    access = 0;
                    type = 0;
                    style = 48;
                    colorBackground[] = {0, 0, 0, 0};
                    font = "TahomaB";
                    sizeEx = 0;
                    lineSpacing = 0;
                    fixedWidth = 0;
                    shadow = 0;
                    tooltipColorText[] = {1, 1, 1, 1};
                    tooltipColorBox[] = {1, 1, 1, 1};
                    tooltipColorShade[] = {0, 0, 0, 0.65};
                };
                class Text {
                    text = "Editor";
                    idc = 1028;
                    size = "1.00 *  (pixelH * pixelGridNoUIScale * 2)";
                    shadow = 2;
                    x = 0;
                    y = 0;
                    w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                    h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                    class Attributes {
                        align = "center";
                        color = "#ffffff";
                        font = "PuristaBold";
                    };
                    deletable = 0;
                    fade = 0;
                    access = 0;
                    type = 13;
                    style = 0;
                    colorText[] = {1, 1, 1, 1};
                };
                class Button {
                    idc = 1026;
                    colorBackground[] = {0, 0, 0, 0};
                    colorBackgroundActive[] = {0, 0, 0, 0};
                    colorBackgroundDisabled[] = {0, 0, 0, 0};
                    colorFocused[] = {0, 0, 0, 0};
                    colorDisabled[] = {0, 0, 0, 0};
                    x = 0;
                    y = 0;
                    w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
                    h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
                    deletable = 0;
                    fade = 0;
                    access = 0;
                    type = 1;
                    text = "";
                    colorText[] = {1, 1, 1, 1};
                    colorShadow[] = {0, 0, 0, 0};
                    colorBorder[] = {0, 0, 0, 1};
                    soundEnter[] = {"\A3\ui_f\data\sound\RscButton\soundEnter", 0.09, 1};
                    soundPush[] = {"\A3\ui_f\data\sound\RscButton\soundPush", 0.09, 1};
                    soundClick[] = {"\A3\ui_f\data\sound\RscButton\soundClick", 0.09, 1};
                    soundEscape[] = {"\A3\ui_f\data\sound\RscButton\soundEscape", 0.09, 1};
                    style = 2;
                    shadow = 2;
                    font = "RobotoCondensed";
                    sizeEx = "(         (           (           ((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
                    url = "";
                    offsetX = 0;
                    offsetY = 0;
                    offsetPressedX = 0;
                    offsetPressedY = 0;
                    borderSize = 0;
                };
            };
            fade = 1;
            y = "0.5 - (    10 / 2) *   (pixelH * pixelGridNoUIScale * 2)";
            w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
            h = "10 *   (pixelH * pixelGridNoUIScale * 2)";
            class VScrollbar {
                width = 0;
                color[] = {1, 1, 1, 1};
                autoScrollEnabled = 1;
                colorActive[] = {1, 1, 1, 1};
                colorDisabled[] = {1, 1, 1, 0.3};
                thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
                arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
                arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
                border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
                shadow = 0;
                scrollSpeed = 0.06;
                height = 0;
                autoScrollSpeed = -1;
                autoScrollDelay = 5;
                autoScrollRewind = 0;
            };
            class HScrollbar {
                height = 0;
                color[] = {1, 1, 1, 1};
                colorActive[] = {1, 1, 1, 1};
                colorDisabled[] = {1, 1, 1, 0.3};
                thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
                arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
                arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
                border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
                shadow = 0;
                scrollSpeed = 0.06;
                width = 0;
                autoScrollEnabled = 0;
                autoScrollSpeed = -1;
                autoScrollDelay = 5;
                autoScrollRewind = 0;
            };
            deletable = 0;
            type = 15;
            shadow = 0;
            style = 16;
        };
        class SpotlightPrev {
            idc = 1060;
            text = "\a3\Ui_f\data\GUI\Rsc\RscDisplayMain\spotlightPrev_ca.paa";
            color[] = {1, 1, 1, 0.25};
            fade = 1;
            x = "0.5 - (0.5 *   10) *   (pixelW * pixelGridNoUIScale * 2)";
            y = "0.5 - (    10 / 2 + (  10 / 8)) *  (pixelH * pixelGridNoUIScale * 2)";
            w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
            h = "(  10 / 8) *   (pixelH * pixelGridNoUIScale * 2)";
            style = "0x30 + 0x800";
            colorActive[] = {1, 1, 1, 1};
            deletable = 0;
            access = 0;
            type = 11;
            colorDisabled[] = {1, 1, 1, 0.25};
            soundEnter[] = {"", 0.1, 1};
            soundPush[] = {"", 0.1, 1};
            soundClick[] = {"", 0.1, 1};
            soundEscape[] = {"", 0.1, 1};
            default = 0;
            font = "RobotoCondensed";
            shadow = 2;
            sizeEx = "(         (           (           ((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
            url = "";
            tooltipColorText[] = {1, 1, 1, 1};
            tooltipColorBox[] = {1, 1, 1, 1};
            tooltipColorShade[] = {0, 0, 0, 0.65};
        };
        class SpotlightNext {
            idc = 1061;
            text = "\a3\Ui_f\data\GUI\Rsc\RscDisplayMain\spotlightNext_ca.paa";
            y = "0.5 + (    10 / 2) *   (pixelH * pixelGridNoUIScale * 2)";
            angle = 180;
            color[] = {1, 1, 1, 0.25};
            fade = 1;
            x = "0.5 - (0.5 *   10) *   (pixelW * pixelGridNoUIScale * 2)";
            w = "10 *   (pixelW * pixelGridNoUIScale * 2)";
            h = "(  10 / 8) *   (pixelH * pixelGridNoUIScale * 2)";
            style = "0x30 + 0x800";
            colorActive[] = {1, 1, 1, 1};
            deletable = 0;
            access = 0;
            type = 11;
            colorDisabled[] = {1, 1, 1, 0.25};
            soundEnter[] = {"", 0.1, 1};
            soundPush[] = {"", 0.1, 1};
            soundClick[] = {"", 0.1, 1};
            soundEscape[] = {"", 0.1, 1};
            default = 0;
            font = "RobotoCondensed";
            shadow = 2;
            sizeEx = "(         (           (           ((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
            url = "";
            tooltipColorText[] = {1, 1, 1, 1};
            tooltipColorBox[] = {1, 1, 1, 1};
            tooltipColorShade[] = {0, 0, 0, 0.65};
        };
    };

    class ControlsBackground {
        class BackgroundLeft {
            colorBackground[] = {0.1, 0.1, 0.1, 1};
            x = "-  10";
            y = "-  10";
            w = "safezoneX +    10";
            h = "2 *    10";
            deletable = 0;
            fade = 0;
            access = 0;
            type = 0;
            idc = -1;
            colorText[] = {1, 1, 1, 1};
            text = "";
            fixedWidth = 0;
            style = 0;
            shadow = 1;
            colorShadow[] = {0, 0, 0, 0.5};
            font = "RobotoCondensed";
            SizeEx = "(         (           (           ((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
            linespacing = 1;
            tooltipColorText[] = {1, 1, 1, 1};
            tooltipColorBox[] = {1, 1, 1, 1};
            tooltipColorShade[] = {0, 0, 0, 0.65};
        };
        class BackgroundRight {
            x = "safezoneX + safezoneW";
            w = 10;
            colorBackground[] = {0.1, 0.1, 0.1, 1};
            y = "-  10";
            h = "2 *    10";
            deletable = 0;
            fade = 0;
            access = 0;
            type = 0;
            idc = -1;
            colorText[] = {1, 1, 1, 1};
            text = "";
            fixedWidth = 0;
            style = 0;
            shadow = 1;
            colorShadow[] = {0, 0, 0, 0.5};
            font = "RobotoCondensed";
            SizeEx = "(         (           (           ((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
            linespacing = 1;
            tooltipColorText[] = {1, 1, 1, 1};
            tooltipColorBox[] = {1, 1, 1, 1};
            tooltipColorShade[] = {0, 0, 0, 0.65};
        };
        class Picture {
            idc = 998;
            text = "\a3\Ui_f\data\GUI\Rsc\RscDisplayMain\backgroundGrey.jpg";
            x = "safezoneX";
            y = "safezoneY";
            w = "safezoneW";
            h = "safezoneW * 4/3";
            deletable = 0;
            fade = 0;
            access = 0;
            type = 0;
            style = 48;
            colorBackground[] = {0, 0, 0, 0};
            colorText[] = {1, 1, 1, 1};
            font = "TahomaB";
            sizeEx = 0;
            lineSpacing = 0;
            fixedWidth = 0;
            shadow = 0;
            tooltipColorText[] = {1, 1, 1, 1};
            tooltipColorBox[] = {1, 1, 1, 1};
            tooltipColorShade[] = {0, 0, 0, 0.65};
        };
    };
};
